# Generated by Django 4.1.2 on 2022-10-27 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='first_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='myuser',
            name='last_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
